# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - feature
    - title: 🎨 UX/UI Updates
      labels:
        - design
    - title: 📚 Content Updates
      labels:
        - content
    - title: 🐛 Bugs Fixed
      labels:
        - bug
    - title: ✅ Testing
      labels:
        - tests
    - title: 🔧 Fixes Applied
      labels:
        - maintenance
    - title: ⚙️ Behind the Scenes
      labels:
        - '*'
