# release.yml

changelog:
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - feature
    - title: 📚 Content Updates
      labels:
        - content
    - title: 🐛 Bugs Fixed
      labels:
        - bug
    - title: ✅ Tests Added
      labels:
        - test
    - title: 🔧 Refactors Made
      labels:
        - refactor
    - title: ⚙️ Behind the Scenes
      labels:
        - '*'
