# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - description-needed
      - good-first-issue
      - help-wanted
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - feature
    - title: 🎨 Content + Design
      labels:
        - content-design
    - title: 🐛 Bugs Fixed
      labels:
        - bug
    - title: ✅ Tests Added
      labels:
        - tests
    - title: 🔧 Maintaining the Code
      labels:
        - refactor
        - maintanence
    - title: ⚙️ Behind the Scenes
      labels:
        - '*'
