# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - feature
    - title: 📚 Content Updates
      labels:
        - content
    - title: 🐛 Bugs Fixed
      labels:
        - bug
    - title: ✅ Tests Added
      labels:
        - tests
    - title: 🔧 Refactors Made
      labels:
        - refactor
    - title: ⚙️ Behind the Scenes
      labels:
        - '*'
