version: '3'

services:

  db:
    image: postgres:14
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - "dbdata:/var/lib/postgres/data"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    platform: linux/x86_64
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://db/lettuceMeetApp_development
      - REDIS_URL=redis://redis:6397
    volumes:
      - .:/app

volumes:
  dbdata: