version: '3'

services:

  db:
    image: postgres:14
    command: postgres -c 'max_connections=250'
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "dbdata:/var/lib/postgres/data"
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  test-api:
    build: ./api
    platform: linux/x86_64
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=${DB_TEST_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    volumes:
      - rails_log:/api/log
    command: "bundle exec rspec spec"

  api:
    build: ./api
    platform: linux/x86_64
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
      - redis
      - test-api
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=${DB_DEV_URL}
      - REDIS_URL=${REDIS_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    volumes:
      - rails_log:/api/log

  
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - front_node_modules:/frontend/node_modules


volumes:
  dbdata:
  rails_log:
  front_node_modules:
