version: '3'

services:

  db:
    image: postgres:14
    command: postgres -c 'max_connections=250'
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - "dbdata:/var/lib/postgres/data"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  test-api:
    build: ./api
    platform: linux/x86_64
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=postgresql://db/lettuceMeetApp_test
      - DB_USER=postgres
      - DB_PASS=changeme
    volumes:
      - rails_log:/api/log
    command: "bundle exec rspec spec"

  api:
    build: ./api
    platform: linux/x86_64
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - test-api
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=postgresql://db/lettuceMeetApp_development
      - REDIS_URL=redis://redis:6397
      - DB_USER=postgres
      - DB_PASS=changeme
    volumes:
      - rails_log:/api/log

  
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - front_node_modules:/client/node_modules


volumes:
  dbdata:
  rails_log:
  front_node_modules:
