version: '3.8'
services:
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=lettuceMeetApp
      - POSTGRES_PASSWORD=leafOnTheWind
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=postgresql://db/lettuceMeetApp_development
      - DB_USER=postgres
      - DB_PASS=leafOnTheWind
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    volumes:
      - .:/lettuceMeetApp
      - bundle:/usr/local/bundle

volumes:
  pg_data:
  redis_data:
  bundle: