version: '3'

services: 

  db:
    image: postgres:14
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - "dbdata:/var/lib/postgres/data"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://db/lettuceMeetApp_development
      - REDIS_URL=redis://redis:6397
      - DB_USER=postgres
      - DB_PASS=changeme
    volumes:
      - .:/api
      - rails_log:/api/log
  
  frontend:
    build: ./frontend
    ports:
      - "8091:8080" # use port that you want to in your local instead of 8091
    volumes:
      - ./frontend:/frontend
      - front_node_modules:/frontend/node_modules


volumes:
  dbdata:
  rails_log:
  front_node_modules:
