# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4'
gem 'dotenv-rails'
gem 'pg', '~> 1.4'

gem 'active_model_serializers', '~> 0.10'
gem 'bootsnap', require: false
gem 'devise'
gem 'devise-jwt'
gem 'fast_jsonapi'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
# DB and JWT management
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'nokogiri', force_ruby_platform: true
gem 'rack-cors'
gem 'redis', '~> 4.0'
gem 'sidekiq', '~> 7.0'

gem "activejob", "~> 7.0"
gem "actionmailer", "~> 7.0"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'

  gem 'bundler-audit'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-nav'

  gem 'rubocop', require: false
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem "letter_opener", "~> 1.8"
  gem "letter_opener_web", "~> 2.0"
end

group :test do
  gem 'capybara'
  gem "webmock"
  gem 'fakeredis'
end
